stock:
  api:
    key: PSnM1hkAFtdj01m82EhCF17APJIpR6m1hV3i
    secret: >-
      rqmtsm+ihaPf7i/taTfE8o9P43TfP3Zt8ITePMdhB4EFye1dU/SSIaA5DVJVK+BvtMHKd9QWiqYQRexoMm1xyQtFbCEPsajdsFPcOpKZrMUivDj3d98O+Jm9Ll9/Ivf8jj45oGw1THoNZVNr5OvOU7DBuLEQbPXNPFipI2XBREoNzgR0xNE=
    base-url: https://openapi.koreainvestment.com:9443/uapi/overseas-price/v1/quotations