version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stock_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0810
      MYSQL_DATABASE: stock_subscription
      MYSQL_USER: cheesecrust
      MYSQL_PASSWORD: 0810
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p0810" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .  # 현재 디렉토리의 Dockerfile 사용
    container_name: stock_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stock_subscription?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: cheesecrust
      SPRING_DATASOURCE_PASSWORD: 0810
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local